default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: vagrant
  host:     localhost
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: dev_dry
test:
  <<: *default
  database: test_dry
